
pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
        
                git branch: 'main', url: 'https://github.com/Bhavani96-V/gravityer.git'
            }
        }

        stage('Build') {
            steps {
                
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                
                sh 'sudo cp /var/lib/jenkins/workspace/web-application/target/*.war /opt/tomcat/webapps/'
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline completed successfully.'
            
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
